const PHRASES = [
    "In my life Ive loved them all",
    "We all live in a yellow submarine",
    "Yesterday all my troubles seemed so far away",
    "All you need is love",
    "Let it be let it be",
    "Hey Jude dont make it bad",
    "She loves you yeah yeah yeah",
    "I want to hold your hand",
    "Help! I need somebody",
    "Strawberry fields forever",
    "Living is easy with eyes closed",
    "Here comes the sun",
    "All the lonely people",
    "Eleanor Rigby picks up the rice",
    "Blackbird singing in the dead of night",
    "Take these broken wings and learn to fly",
    "Nothings gonna change my world",
    "Jai guru deva om",
    "The movement you need is on your shoulder",
    "The love you take is equal to",
    "the love you make",
    "Lucy in the sky with diamonds",
    "I am the walrus",
    "Goo goo gjoob",
    "Penny Lane is in my ears",
    "I read the news today oh boy",
    "A day in the life",
    "Come together right now over me",
    "Yellow matter custard dripping from a dead dogs eye",
    "Semolina pilchard climbing up the Eiffel Tower",
    "Something in the way she moves",
    "Love love me do",
    "Cant buy me love",
    "Michelle ma belle",
    "Dont let me down",
    "Ill follow the sun",
    "Eight days a week",
    "Shes leaving home after living alone",
    "And I love her",
    "I’ve just seen a face",
    "Its been a hard days night",
    "Ob-la-di ob-la-da life goes on",
    "Hes a real nowhere man",
    "Paperback writer",
    "Get back to where you once belonged",
    "You say you want a revolution",
    "While my guitar gently weeps",
    "With a little help from my friends",
    "The long and winding road",
    "We can work it out",
    "She was just seventeen you know what I mean",
    "Close your eyes and Ill kiss you",
    "All my loving I will send to you",
    "I saw her standing there",
    "Im in love with her and I feel fine",
    "It wont be long yeah yeah yeah",
    "Wait till I come back to your side",
    "Tell me what you see",
    "Ill buy you a diamond ring my friend",
    "I should have known better with a girl",
    "If I fell in love with you",
    "Im happy just to dance with you",
    "Youre going to lose that girl",
    "Money dont get everything its true",
    "I think Im gonna be sad",
    "Ill cry instead",
    "Every little thing she does",
    "Im a loser",
    "Eight days a week is not enough",
    "The night before",
    "The girl with kaleidoscope eyes",
    "Turn off your mind relax and float downstream",
    "Lay down all thoughts surrender to the void",
    "Listen to the color of your dreams",
    "I am the eggman they are the eggmen",
    "Expert texpert choking smokers",
    "Look for the girl with the sun",
    "Picture yourself in a boat on a river",
    "Climb up the Eiffel Tower",
    "Newspaper taxis appear on the shore",
    "Waiting for the sun",
    "Magical mystery tour is coming to take you",
    "The fool on the hill sees the sun",
    "Sitting on a cornflake waiting for the van",
    "Man you should have seen them kicking Edgar",
    "Words are flowing out like endless rain",
    "Images of broken light which dance before me",
    "Limitless undying love which shines around me",
    "Always no sometimes think its me",
    "Let me take you down",
    "Nothing is real",
    "Im looking through you where did you go",
    "In my life I love you more",
    "There are places Ill remember",
    "Father McKenzie writing the words",
    "Eleanor Rigby died in the church",
    "All the lonely people where do they belong",
    "For no one",
    "A love that should have lasted years",
    "Shes got a ticket to ride",
    "Hes as blind as he can be",
    "Isnt it good Norwegian wood",
    "Think for yourself cause I wont be there",
    "Ive got to get you into my life",
    "Here there and everywhere",
    "Michelle ma belle these are words",
    "Life is very short",
    "Theres no time for fussing and fighting",
    "Try to see it my way",
    "Life goes on within you and without you",
    "When Im sixty-four",
    "Will you still need me will you still",
    "I get high with a little help",
    "Fixing a hole where the rain gets in",
    "Woke up fell out of bed",
    "Dragged a comb across my head",
    "Id love to turn you on",
    "Shes leaving home bye bye",
    "Its getting better all the time",
    "Blackbird fly blackbird fly",
    "Into the light of the dark black night",
    "Julia ocean child calls me",
    "Sexy Sadie what have you done",
    "Im so tired I havent slept a wink",
    "Back in the USSR",
    "Maxwells silver hammer came down",
    "Bang bang Maxwells silver hammer",
    "Id like to be under the sea",
    "In an octopuss garden in the shade",
    "Because the world is round",
    "Mean Mr Mustard sleeps in the park",
    "She came in through the bathroom window",
    "Golden slumbers fill your eyes",
    "Smiles awake you when you rise",
    "Boy youre gonna carry that weight",
    "Two of us riding nowhere"
];
